"""Bounded live evaluation. No provider calls without explicit `run --authorized`.
Only durable public tool entries and numeric usage are analyzed; no transport trace.
"""
import argparse
import collections
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import time

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent.parent
RESULTS = ROOT / "results"
FLAGS = subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0
TOOLCHAIN = Path.home() / "scoop/persist/rustup-msvc/.rustup/toolchains/stable-x86_64-pc-windows-msvc/bin"
CONFIG = '''model = "gpt-5.6-luna"
effort = "high"
codex_fast = false
max_turns = 20
max_total_tool_calls = 40
max_read_tool_calls = 32
max_mutating_tool_calls = 12
timeout_secs = 180
[lsp]
enabled = true
request_timeout_ms = 30000
'''


def dump(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def sha(data):
    return hashlib.sha256(data).hexdigest()


def put(root, files):
    for name, content in files.items():
        p = root / name
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(content.encode())


def env():
    result = dict(os.environ)
    # Explicit isolated run config, without changing global configuration or credentials.
    for key in list(result):
        if key.startswith("SLIM_") and not any(s in key for s in ("KEY", "TOKEN", "AUTH")):
            result.pop(key)
    result.update(SLIM_CONFIG_FILE=str(ROOT / "config.toml"),
                  RUSTC=str(TOOLCHAIN / "rustc.exe"),
                  RUSTDOC=str(TOOLCHAIN / "rustdoc.exe"),
                  CARGO_BUILD_JOBS="1", RUSTC_WRAPPER="")
    return result


def command(args, cwd, timeout=120):
    return subprocess.run(args, cwd=cwd, env=env(), capture_output=True,
                          creationflags=FLAGS, timeout=timeout)


def cases():
    base = {
        "Cargo.toml": '[package]\nname = "route_fixture"\nversion = "0.1.0"\nedition = "2021"\n\n[workspace]\n',
        "Cargo.lock": '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "route_fixture"\nversion = "0.1.0"\n',
        "src/lib.rs": 'pub mod billing;\npub mod legacy;\npub mod checkout;\npub mod reports;\npub mod catalog;\npub mod delivery;\n',
        "src/billing.rs": 'pub fn charge_total(cents: u32) -> u32 {\n    cents + 25\n}\n\npub fn retry_key() -> &\'static str {\n    "transport.retry_limit"\n}\n',
        "src/legacy.rs": 'pub fn charge_total(cents: u32) -> u32 {\n    cents + 900\n}\n\npub fn retry_key() -> &\'static str {\n    "legacy.retry_limit"\n}\n',
        "src/checkout.rs": 'use crate::billing::charge_total as calculate;\n\npub fn submit(cents: u32) -> u32 {\n    calculate(cents)\n}\n\npub const LABEL: &str = "charge_total";\n',
        "src/reports.rs": 'pub fn invoice(cents: u32) -> u32 {\n    crate::billing::charge_total(cents)\n}\n\npub fn old_invoice(cents: u32) -> u32 {\n    crate::legacy::charge_total(cents)\n}\n\n// charge_total is the name printed by the historic exporter.\npub const EXPORT_TAG: &str = "billing::charge_total";\n',
        "src/delivery.rs": 'use crate::billing::retry_key as active_key;\n\npub fn setting_name() -> &\'static str {\n    active_key()\n}\n',
        "src/catalog.rs": ''.join(f'pub fn noise_{i:03}(x: u32) -> u32 {{ x + {i} }}\n' for i in range(160)) + '\npub struct ExportPolicy;\nimpl ExportPolicy {\n    pub fn zeta_export_window(&self, rows: usize, cap: usize) -> Option<usize> {\n        (cap > 0).then_some(rows.min(cap))\n    }\n}\n',
        "config/runtime.json": '{\n  "transport.retry_limit": 3,\n  "legacy.retry_limit": 9,\n  "receipt.message": "Payment pending",\n  "receipt.comment": "Payment pending is a historical label"\n}\n',
        "docs/history.txt": 'charge_total and billing::charge_total are historical text, not calls.\nPayment pending\ntransport.retry_limit is the old key.\n',
    }
    result = {}
    common = "Trabalhe somente neste workspace descartável. Preserve arquivos fora do objetivo. Grave resposta estruturada em answer.json, sem Markdown. "
    def add(key, prompt, expected, answer):
        result[key] = dict(files=base.copy(), prompt=common + prompt, expected=expected, answer=answer)
    add("A", 'checkout::submit chama um cálculo por alias. Localize implementação efetiva, altere somente sua taxa de 25 para 40 centavos e preserve caminho legado. Em answer.json informe implementation (arquivo), signature (assinatura pública completa, sem corpo) e return_type. Valide comportamento.',
        {"src/billing.rs": base["src/billing.rs"].replace("cents + 25", "cents + 40")},
        dict(implementation="src/billing.rs", signature="pub fn charge_total(cents: u32) -> u32", return_type="u32"))
    add("B", 'Renomeie billing::charge_total para invoice_total e ajuste somente usos semânticos desse símbolo. Preserve alias local calculate, função homônima legada, strings e comentários. Em answer.json liste reference_files: arquivos com referências ao símbolo fora da definição, sem duplicatas. Valide compilação.',
        {"src/billing.rs": base["src/billing.rs"].replace("fn charge_total", "fn invoice_total"),
         "src/checkout.rs": base["src/checkout.rs"].replace("billing::charge_total", "billing::invoice_total"),
         "src/reports.rs": base["src/reports.rs"].replace("crate::billing::charge_total(cents)", "crate::billing::invoice_total(cents)")},
        dict(reference_files=["src/checkout.rs", "src/reports.rs"]))
    add("C", 'Em src/catalog.rs identifique método zeta_export_window, seu tipo contêiner e assinatura. Não altere código. Em answer.json informe path, container, signature (assinatura pública completa sem corpo) e return_type.', {},
        dict(path="src/catalog.rs", container="ExportPolicy", signature="pub fn zeta_export_window(&self, rows: usize, cap: usize) -> Option<usize>", return_type="Option<usize>"))
    add("D", 'Troque mensagem de recibo ativa de Payment pending para Payment queued na configuração runtime. Preserve comentário e documentação histórica com texto semelhante. Não altere Rust. Em answer.json informe path e key da configuração alterada.',
        {"config/runtime.json": base["config/runtime.json"].replace('"receipt.message": "Payment pending"', '"receipt.message": "Payment queued"')},
        dict(path="config/runtime.json", key="receipt.message"))
    add("E", 'delivery::setting_name resolve uma chave por alias. Descubra implementação efetiva e migre chave ativa de transport.retry_limit para transport.max_attempts no código e configuração runtime, mantendo valor 3. Preserve chave legada e documentação histórica. Em answer.json informe implementation (arquivo), signature (assinatura pública da implementação sem corpo), config_path e new_key. Valide comportamento.',
        {"src/billing.rs": base["src/billing.rs"].replace('"transport.retry_limit"', '"transport.max_attempts"'),
         "config/runtime.json": base["config/runtime.json"].replace('"transport.retry_limit"', '"transport.max_attempts"')},
        dict(implementation="src/billing.rs", signature="pub fn retry_key() -> &'static str", config_path="config/runtime.json", new_key="transport.max_attempts"))
    return result


def normalized(content):
    # Only formatting tolerance. Exact text in string literals remains protected separately.
    return "".join(content.split())


def validate(key, work):
    spec = cases()[key]
    checks = {}
    for name, initial in spec["files"].items():
        path = work / name
        actual = path.read_bytes() if path.is_file() else b""
        expected = spec["expected"].get(name, initial).encode()
        if name in spec["expected"] and name.endswith(".json"):
            try:
                checks[name] = json.loads(actual) == json.loads(expected)
            except (ValueError, UnicodeError):
                checks[name] = False
        elif name in spec["expected"]:
            # Exact expected localized transformation, whitespace tolerance only.
            checks[name] = normalized(actual.decode(errors="replace")) == normalized(expected.decode())
            # Prevent whitespace tolerance from weakening string/comment preservation.
            import re
            checks[name] &= re.findall(r'"[^"\n]*"|//[^\n]*', actual.decode(errors="replace")) == re.findall(r'"[^"\n]*"|//[^\n]*', expected.decode())
        else:
            checks[name] = actual == expected
    try:
        answer = json.loads((work / "answer.json").read_text(encoding="utf-8-sig"))
    except (OSError, ValueError):
        answer = {}
    for field, expected in spec["answer"].items():
        actual = answer.get(field)
        if field == "signature" and isinstance(actual, str):
            checks["answer." + field] = normalized(actual) == normalized(expected)
        elif isinstance(expected, list):
            checks["answer." + field] = isinstance(actual, list) and sorted(actual) == sorted(expected)
        else:
            checks["answer." + field] = actual == expected
    added = [p.relative_to(work).as_posix() for p in work.rglob("*") if p.is_file()
             and not set(p.relative_to(work).parts) & {"target", ".slim", ".git"}
             and p.relative_to(work).as_posix() not in spec["files"]
             and p.relative_to(work).as_posix() != "answer.json"]
    # Additional tests allowed, unrelated production files not allowed.
    checks["no_unrelated_files"] = all(p.startswith("tests/") for p in added)
    validation_work = Path(tempfile.mkdtemp(prefix=f"slim-acceptance-{key}-"))
    shutil.copytree(work, validation_work, dirs_exist_ok=True,
                    ignore=shutil.ignore_patterns("target", ".slim", ".git"))
    fee = 40 if key == "A" else 25
    active_key = "transport.max_attempts" if key == "E" else "transport.retry_limit"
    acceptance = f'''use route_fixture::*;
#[test]
fn independent_behavior() {{
    for cents in [0, 1, 100, 99999] {{
        assert_eq!(checkout::submit(cents), cents + {fee});
        assert_eq!(reports::invoice(cents), cents + {fee});
        assert_eq!(reports::old_invoice(cents), cents + 900);
    }}
    assert_eq!(delivery::setting_name(), "{active_key}");
    assert_eq!(legacy::retry_key(), "legacy.retry_limit");
    assert_eq!(checkout::LABEL, "charge_total");
    assert_eq!(reports::EXPORT_TAG, "billing::charge_total");
    assert_eq!(catalog::ExportPolicy.zeta_export_window(8, 3), Some(3));
    assert_eq!(catalog::ExportPolicy.zeta_export_window(8, 0), None);
}}
'''
    if key == "B":
        acceptance += '#[test]\nfn renamed_api() { assert_eq!(billing::invoice_total(100), 125); }\n'
    put(validation_work, {"tests/agentic_acceptance.rs": acceptance})
    test = command(["cargo", "test", "--offline", "--locked"], validation_work)
    checks["cargo_test"] = test.returncode == 0
    success = all(checks.values())
    changed_ok = any(checks[n] for n in spec["expected"]) if spec["expected"] else any(checks[k] for k in checks if k.startswith("answer."))
    return dict(correctness="sucesso" if success else "sucesso parcial" if changed_ok else "falha",
                checks=checks, unexpected_files=added, cargo_exit=test.returncode,
                cargo_output=(test.stdout + test.stderr).decode(errors="replace"))


def prepare():
    ROOT.mkdir(parents=True, exist_ok=True)
    (ROOT / "config.toml").write_text(CONFIG, encoding="utf-8")
    manifest = {}
    for key, spec in cases().items():
        dest = ROOT / "initial" / key
        if dest.exists():
            raise RuntimeError(f"refusing to overwrite {dest}")
        put(dest, spec["files"])
        # Objectives and oracles stay outside agent workspace.
        (ROOT / f"prompt-{key}.txt").write_text(spec["prompt"], encoding="utf-8")
        manifest[key] = {n: sha(c.encode()) for n, c in spec["files"].items()}
    dump(ROOT / "fixtures.json", manifest)
    binary = REPO / "target/release/slim.exe"
    sources = json.loads((RESULTS / "preexisting.json").read_text())
    sources = {p: h for p, h in sources.items() if p.startswith(("crates/", "tests/", ".cargo/")) or p in ("Cargo.toml", "Cargo.lock")}
    dump(RESULTS / "baseline.json", dict(head=command(["git", "rev-parse", "HEAD"], REPO).stdout.decode().strip(),
         dirty=True, sources=sources, sources_sha256=sha(json.dumps(sources, sort_keys=True).encode()),
         binary=str(binary), binary_sha256=sha(binary.read_bytes()), config_sha256=sha((ROOT / "config.toml").read_bytes()),
         model="gpt-5.6-luna", provider="openai-codex", effort="high", fast=False, repetitions=2,
         run_order=[f"{k}-{rep}" for rep in (1, 2) for k in cases()],
         authorization="User: autorizo, gpt luna high , do provider do codex"))


def selftest():
    report = {}
    for key, spec in cases().items():
        work = Path(tempfile.mkdtemp(prefix=f"slim-oracle-{key}-"))
        put(work, spec["files"])
        bad = validate(key, work)
        put(work, spec["expected"])
        dump(work / "answer.json", spec["answer"])
        good = validate(key, work)
        # Protected textual false positive must fail even with correct answer/code.
        with (work / "docs/history.txt").open("a") as f:
            f.write("changed\n")
        poisoned = validate(key, work)
        assert bad["correctness"] != "sucesso", (key, bad)
        assert good["correctness"] == "sucesso", (key, good)
        assert not poisoned["checks"]["docs/history.txt"], key
        report[key] = dict(workspace=str(work), initial=bad, canonical=good, protected_mutation=poisoned)
    dump(RESULTS / "oracle-tests.json", report)
    print("5 initial rejected; 5 canonical accepted; 5 protected mutations rejected")


def run(key, rep):
    spec = cases()[key]
    out = RESULTS / f"{key}-{rep}"
    out.mkdir(exist_ok=False)
    baseline = json.loads((RESULTS / "baseline.json").read_text())
    binary = Path(baseline["binary"])
    assert sha(binary.read_bytes()) == baseline["binary_sha256"], "binary changed"
    assert sha((ROOT / "config.toml").read_bytes()) == baseline["config_sha256"], "config changed"
    assert (ROOT / f"prompt-{key}.txt").read_text(encoding="utf-8") == spec["prompt"], "prompt changed"
    work = Path(tempfile.mkdtemp(prefix=f"slim-agentic-{key}-{rep}-"))
    shutil.copytree(ROOT / "initial" / key, work, dirs_exist_ok=True)
    assert {p.relative_to(work).as_posix(): sha(p.read_bytes()) for p in work.rglob("*") if p.is_file()} == json.loads((ROOT / "fixtures.json").read_text())[key]
    args = [str(binary), "--headless", "--jsonl", "--provider", "openai-codex", "--model", "gpt-5.6-luna",
            "--effort", "high", "--normal", "--session", str(out / "session.jsonl"), "--prompt", spec["prompt"]]
    started = dt.datetime.now(dt.timezone.utc).isoformat()
    timer = time.perf_counter()
    dump(out / "run.json", dict(workspace=str(work), started=started, args=args, state="running"))
    # stdout is only final JSON; durable writer strips private reasoning at source.
    with (out / "result.jsonl").open("wb") as stdout, (out / "stderr.txt").open("wb") as stderr:
        proc = subprocess.Popen(args, cwd=work, env=env(), stdout=stdout, stderr=stderr, creationflags=FLAGS)
        try:
            exit_code = proc.wait(timeout=900)
        except subprocess.TimeoutExpired:
            # Scoped process tree only, never an installed Slim or desktop session.
            subprocess.run(["taskkill", "/PID", str(proc.pid), "/T", "/F"], capture_output=True, creationflags=FLAGS)
            proc.wait()
            exit_code = "timeout"
    wall = dict(workspace=str(work), started=started, ended=dt.datetime.now(dt.timezone.utc).isoformat(),
                wall_ms=(time.perf_counter()-timer)*1000, args=args, exit_code=exit_code, state="finished")
    dump(out / "run.json", wall)
    dump(out / "check.json", validate(key, work))
    print(key, rep, exit_code, flush=True)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("mode", choices=["prepare", "selftest", "run"])
    p.add_argument("--authorized", action="store_true")
    p.add_argument("--case", choices=list(cases()))
    p.add_argument("--rep", type=int, choices=[1, 2])
    a = p.parse_args()
    if a.mode == "prepare":
        prepare()
    elif a.mode == "selftest":
        selftest()
    else:
        if not a.authorized or not a.case or not a.rep:
            p.error("run requires --authorized --case A..E --rep 1..2")
        run(a.case, a.rep)


if __name__ == "__main__":
    main()
